# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://alquilerautosrara.c60l4nytl1em.sa-east-1.rds.amazonaws.com:3306/alquilerautosrara
    username: root
    password: root123qp

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = MAIL configurations
# ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: alquilerautosrara@gmail.com
    password: alquilerautosrara123
    port: 587
    #host: mailrelay.intranet.hdp.be
    #username: test
    #password: test
    #port:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    
#server:
#  port: 9000